<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="ResQ.BuildingBlocks.Application" />
    <ProjectReference Include="..\ResQ.Service.Domain\ResQ.Service.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
  </ItemGroup>

</Project>
